name: Release

on:
  push:
    branches: [ master ]
    tags:
      - 'v*'

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag semantic-release-with-release-docker:${{ github.ref_name }}
      - name: Log in to the Container registry
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push the latest Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: feriva22/semantic-release-with-release-docker:latest
      - name: Push the Docker image with the release tag
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: feriva22/semantic-release-with-release-docker:${{ github.ref_name}}